// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const isWebhookDelivered = `-- name: IsWebhookDelivered :one
SELECT EXISTS (
    SELECT 1 FROM webhook_deliveries
    WHERE event_id = $1 AND webhook_id = $2
)
`

type IsWebhookDeliveredParams struct {
	EventID   string    `json:"event_id"`
	WebhookID uuid.UUID `json:"webhook_id"`
}

func (q *Queries) IsWebhookDelivered(ctx context.Context, arg IsWebhookDeliveredParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWebhookDelivered, arg.EventID, arg.WebhookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :execrows
INSERT INTO webhook_deliveries (event_id, webhook_id)
VALUES ($1, $2)
ON CONFLICT (event_id, webhook_id) DO NOTHING
`

type MarkWebhookDeliveredParams struct {
	EventID   string    `json:"event_id"`
	WebhookID uuid.UUID `json:"webhook_id"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookDelivered, arg.EventID, arg.WebhookID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
