package message

import (
	"encoding/json"
	"net/http"
	"strconv"
	"time"

	_ "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/mesewo/slack-clone/apps/api/internal/auth"
	db "github.com/mesewo/slack-clone/apps/api/internal/database"
	"github.com/mesewo/slack-clone/apps/api/internal/gateway"
)

type MessageHandler struct {
	Queries *db.Queries
	Hub     *gateway.Hub
}

type CreateMessageRequest struct {
	ChannelID string `json:"channel_id"`
	Content   string `json:"content"`
}

// SendMessage persists a message using sqlc and broadcasts it via WebSocket
func (h *MessageHandler) SendMessage(w http.ResponseWriter, r *http.Request) {
	claims, ok := r.Context().Value(auth.UserContextKey).(*auth.Claims)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	var req CreateMessageRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid payload", http.StatusBadRequest)
		return
	}

	// Parse string UUIDs into pgtype.UUID for pgx/v5 sqlc drivers
	var channelUUID pgtype.UUID
	if err := channelUUID.Scan(req.ChannelID); err != nil {
		http.Error(w, "Invalid channel ID", http.StatusBadRequest)
		return
	}

	var userUUID pgtype.UUID
	if err := userUUID.Scan(claims.UserID); err != nil {
		http.Error(w, "Invalid user ID", http.StatusBadRequest)
		return
	}

	// Execute type-safe query generated by sqlc
	msg, err := h.Queries.CreateMessage(r.Context(), db.CreateMessageParams{
		ChannelID: channelUUID,
		UserID:    userUUID,
		Content:   req.Content,
	})
	if err != nil {
		http.Error(w, "Failed to save message", http.StatusInternalServerError)
		return
	}

	// Broadcast the newly created message struct directly to the WebSocket hub
	msgBytes, err := json.Marshal(msg)
	if err == nil {
		h.Hub.BroadcastToChannel(req.ChannelID, msgBytes)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(msg)
}

// GetChannelMessages fetches paginated message history for a channel
func (h *MessageHandler) GetChannelMessages(w http.ResponseWriter, r *http.Request) {
	channelID := r.URL.Query().Get("channel_id")
	if channelID == "" {
		http.Error(w, "Missing channel_id parameter", http.StatusBadRequest)
		return
	}

	var channelUUID pgtype.UUID
	if err := channelUUID.Scan(channelID); err != nil {
		http.Error(w, "Invalid channel ID", http.StatusBadRequest)
		return
	}

	limit := int32(50)

	if limitStr := r.URL.Query().Get("limit"); limitStr != "" {
		if l, err := strconv.Atoi(limitStr); err == nil {
			limit = int32(l)
		}
	}

	// For the initial page, the query expects a cursor timestamp representing
	// the upper bound (created_at < cursor). Use now() when the client does
	// not provide a `cursor` parameter so the most recent messages are returned.
	var createdAt time.Time
	if cursor := r.URL.Query().Get("cursor"); cursor != "" {
		// If client sends an RFC3339 timestamp cursor, try to parse it.
		if t, err := time.Parse(time.RFC3339, cursor); err == nil {
			createdAt = t
		} else {
			// fallback to now on parse error
			createdAt = time.Now()
		}
	} else {
		createdAt = time.Now()
	}

	// Fetch messages using sqlc typed query
	messages, err := h.Queries.ListChannelMessages(r.Context(), db.ListChannelMessagesParams{
		ChannelID: channelUUID,
		CreatedAt: createdAt,
		Limit:     limit,
	})
	if err != nil {
		http.Error(w, "Failed to fetch messages", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(messages)
}