// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/rpc/proto/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Pre-marshaled WSEvent JSON. Gateway doesn't need to understand the
	// payload's shape - it just relays bytes to subscribed connections.
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *BroadcastRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_chat_proto_rawDescGZIP(), []int{1}
}

type GetUserChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChannelsRequest) Reset() {
	*x = GetUserChannelsRequest{}
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChannelsRequest) ProtoMessage() {}

func (x *GetUserChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetUserChannelsRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserChannelsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelIds    []string               `protobuf:"bytes,1,rep,name=channel_ids,json=channelIds,proto3" json:"channel_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChannelsResponse) Reset() {
	*x = GetUserChannelsResponse{}
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChannelsResponse) ProtoMessage() {}

func (x *GetUserChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetUserChannelsResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserChannelsResponse) GetChannelIds() []string {
	if x != nil {
		return x.ChannelIds
	}
	return nil
}

var File_internal_rpc_proto_chat_proto protoreflect.FileDescriptor

const file_internal_rpc_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/rpc/proto/chat.proto\x12\x04chat\"K\n" +
	"\x10BroadcastRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x13\n" +
	"\x11BroadcastResponse\"1\n" +
	"\x16GetUserChannelsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x17GetUserChannelsResponse\x12\x1f\n" +
	"\vchannel_ids\x18\x01 \x03(\tR\n" +
	"channelIds2N\n" +
	"\x0eGatewayService\x12<\n" +
	"\tBroadcast\x12\x16.chat.BroadcastRequest\x1a\x17.chat.BroadcastResponse2]\n" +
	"\vCoreService\x12N\n" +
	"\x0fGetUserChannels\x12\x1c.chat.GetUserChannelsRequest\x1a\x1d.chat.GetUserChannelsResponseB<Z:github.com/mesewo/slack-clone/apps/api/internal/rpc/chatpbb\x06proto3"

var (
	file_internal_rpc_proto_chat_proto_rawDescOnce sync.Once
	file_internal_rpc_proto_chat_proto_rawDescData []byte
)

func file_internal_rpc_proto_chat_proto_rawDescGZIP() []byte {
	file_internal_rpc_proto_chat_proto_rawDescOnce.Do(func() {
		file_internal_rpc_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_chat_proto_rawDesc), len(file_internal_rpc_proto_chat_proto_rawDesc)))
	})
	return file_internal_rpc_proto_chat_proto_rawDescData
}

var file_internal_rpc_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_rpc_proto_chat_proto_goTypes = []any{
	(*BroadcastRequest)(nil),        // 0: chat.BroadcastRequest
	(*BroadcastResponse)(nil),       // 1: chat.BroadcastResponse
	(*GetUserChannelsRequest)(nil),  // 2: chat.GetUserChannelsRequest
	(*GetUserChannelsResponse)(nil), // 3: chat.GetUserChannelsResponse
}
var file_internal_rpc_proto_chat_proto_depIdxs = []int32{
	0, // 0: chat.GatewayService.Broadcast:input_type -> chat.BroadcastRequest
	2, // 1: chat.CoreService.GetUserChannels:input_type -> chat.GetUserChannelsRequest
	1, // 2: chat.GatewayService.Broadcast:output_type -> chat.BroadcastResponse
	3, // 3: chat.CoreService.GetUserChannels:output_type -> chat.GetUserChannelsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_rpc_proto_chat_proto_init() }
func file_internal_rpc_proto_chat_proto_init() {
	if File_internal_rpc_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_chat_proto_rawDesc), len(file_internal_rpc_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_rpc_proto_chat_proto_goTypes,
		DependencyIndexes: file_internal_rpc_proto_chat_proto_depIdxs,
		MessageInfos:      file_internal_rpc_proto_chat_proto_msgTypes,
	}.Build()
	File_internal_rpc_proto_chat_proto = out.File
	file_internal_rpc_proto_chat_proto_goTypes = nil
	file_internal_rpc_proto_chat_proto_depIdxs = nil
}
