// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (channel_id, user_id)
VALUES ($1, $2)
`

type AddChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.Exec(ctx, addChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (workspace_id, name, type, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, type, created_by, created_at
`

type CreateChannelParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.CreatedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS (
    SELECT 1 FROM channel_members
    WHERE channel_id = $1 AND user_id = $2
)
`

type IsChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChannelsForUser = `-- name: ListChannelsForUser :many
SELECT c.id, c.workspace_id, c.name, c.type, c.created_by, c.created_at FROM channels c
JOIN channel_members cm ON cm.channel_id = c.id
WHERE cm.user_id = $1 AND c.workspace_id = $2
ORDER BY c.name
`

type ListChannelsForUserParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ListChannelsForUser(ctx context.Context, arg ListChannelsForUserParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForUser, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastRead = `-- name: UpdateLastRead :exec
UPDATE channel_members
SET last_read_at = now()
WHERE channel_id = $1 AND user_id = $2
`

type UpdateLastReadParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, updateLastRead, arg.ChannelID, arg.UserID)
	return err
}
