// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: direct_messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDirectConversationMember = `-- name: AddDirectConversationMember :exec
INSERT INTO direct_conversation_members (conversation_id, user_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddDirectConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AddDirectConversationMember(ctx context.Context, arg AddDirectConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addDirectConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createDirectConversation = `-- name: CreateDirectConversation :one
INSERT INTO direct_conversations (created_by) VALUES ($1) RETURNING id, created_by, created_at
`

func (q *Queries) CreateDirectConversation(ctx context.Context, createdBy uuid.UUID) (DirectConversation, error) {
	row := q.db.QueryRow(ctx, createDirectConversation, createdBy)
	var i DirectConversation
	err := row.Scan(&i.ID, &i.CreatedBy, &i.CreatedAt)
	return i, err
}

const createDirectMessage = `-- name: CreateDirectMessage :one
INSERT INTO direct_messages (conversation_id, user_id, content)
VALUES ($1, $2, $3) RETURNING id, conversation_id, user_id, content, created_at, updated_at, deleted_at, parent_id, reply_count
`

type CreateDirectMessageParams struct {
	ConversationID uuid.UUID     `json:"conversation_id"`
	UserID         uuid.NullUUID `json:"user_id"`
	Content        string        `json:"content"`
}

func (q *Queries) CreateDirectMessage(ctx context.Context, arg CreateDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, createDirectMessage, arg.ConversationID, arg.UserID, arg.Content)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
		&i.ReplyCount,
	)
	return i, err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT dc.id, dc.created_by, dc.created_at
FROM direct_conversations dc
JOIN direct_conversation_members a ON a.conversation_id = dc.id AND a.user_id = $1
JOIN direct_conversation_members b ON b.conversation_id = dc.id AND b.user_id = $2
WHERE (SELECT COUNT(*) FROM direct_conversation_members m WHERE m.conversation_id = dc.id) = 2
LIMIT 1
`

type FindDirectConversationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (DirectConversation, error) {
	row := q.db.QueryRow(ctx, findDirectConversation, arg.UserID, arg.UserID_2)
	var i DirectConversation
	err := row.Scan(&i.ID, &i.CreatedBy, &i.CreatedAt)
	return i, err
}

const isDirectConversationMember = `-- name: IsDirectConversationMember :one
SELECT EXISTS (
  SELECT 1 FROM direct_conversation_members
  WHERE conversation_id = $1 AND user_id = $2
)
`

type IsDirectConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsDirectConversationMember(ctx context.Context, arg IsDirectConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDirectConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDirectConversationsForUser = `-- name: ListDirectConversationsForUser :many
SELECT dc.id, dc.created_by, dc.created_at,
       u.id AS other_user_id, u.display_name AS other_display_name, u.email AS other_email
FROM direct_conversations dc
JOIN direct_conversation_members mine ON mine.conversation_id = dc.id AND mine.user_id = $1
JOIN direct_conversation_members other ON other.conversation_id = dc.id AND other.user_id <> $1
JOIN users u ON u.id = other.user_id
ORDER BY dc.created_at DESC
`

type ListDirectConversationsForUserRow struct {
	ID               uuid.UUID `json:"id"`
	CreatedBy        uuid.UUID `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
	OtherUserID      uuid.UUID `json:"other_user_id"`
	OtherDisplayName string    `json:"other_display_name"`
	OtherEmail       string    `json:"other_email"`
}

func (q *Queries) ListDirectConversationsForUser(ctx context.Context, userID uuid.UUID) ([]ListDirectConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listDirectConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectConversationsForUserRow
	for rows.Next() {
		var i ListDirectConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.OtherUserID,
			&i.OtherDisplayName,
			&i.OtherEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectMessages = `-- name: ListDirectMessages :many
SELECT dm.id, dm.conversation_id, dm.user_id, dm.content, dm.created_at, dm.updated_at, dm.deleted_at, dm.parent_id, dm.reply_count, u.display_name AS author_name
FROM direct_messages dm
LEFT JOIN users u ON u.id = dm.user_id
WHERE dm.conversation_id = $1 AND dm.deleted_at IS NULL
ORDER BY dm.created_at ASC
`

type ListDirectMessagesRow struct {
	ID             uuid.UUID     `json:"id"`
	ConversationID uuid.UUID     `json:"conversation_id"`
	UserID         uuid.NullUUID `json:"user_id"`
	Content        string        `json:"content"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      *time.Time    `json:"updated_at"`
	DeletedAt      *time.Time    `json:"deleted_at"`
	ParentID       uuid.NullUUID `json:"parent_id"`
	ReplyCount     int32         `json:"reply_count"`
	AuthorName     pgtype.Text   `json:"author_name"`
}

func (q *Queries) ListDirectMessages(ctx context.Context, conversationID uuid.UUID) ([]ListDirectMessagesRow, error) {
	rows, err := q.db.Query(ctx, listDirectMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectMessagesRow
	for rows.Next() {
		var i ListDirectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
			&i.ReplyCount,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForDM = `-- name: ListUsersForDM :many
SELECT id, email, display_name, created_at, updated_at
FROM users WHERE id <> $1 ORDER BY display_name, email
`

type ListUsersForDMRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListUsersForDM(ctx context.Context, id uuid.UUID) ([]ListUsersForDMRow, error) {
	rows, err := q.db.Query(ctx, listUsersForDM, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForDMRow
	for rows.Next() {
		var i ListUsersForDMRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
