// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, user_id, content, created_at, updated_at, deleted_at, parent_id, reply_count
`

type CreateMessageParams struct {
	ChannelID uuid.UUID     `json:"channel_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Content   string        `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChannelID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
		&i.ReplyCount,
	)
	return i, err
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT id, channel_id, user_id, content, created_at, updated_at, deleted_at, parent_id, reply_count FROM messages
WHERE channel_id = $1
  AND created_at < $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3
`

type ListChannelMessagesParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

// Cursor pagination: pass the created_at of the oldest message you already have
// to get the next (older) page. For the first page, pass now() as the cursor.
func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, arg.ChannelID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
