// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspaceWebhook = `-- name: CreateWorkspaceWebhook :one
INSERT INTO workspace_webhooks (workspace_id, url, secret)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, url, secret, created_at, updated_at
`

type CreateWorkspaceWebhookParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Url         string    `json:"url"`
	Secret      string    `json:"secret"`
}

func (q *Queries) CreateWorkspaceWebhook(ctx context.Context, arg CreateWorkspaceWebhookParams) (WorkspaceWebhook, error) {
	row := q.db.QueryRow(ctx, createWorkspaceWebhook, arg.WorkspaceID, arg.Url, arg.Secret)
	var i WorkspaceWebhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceWebhook = `-- name: DeleteWorkspaceWebhook :execrows
DELETE FROM workspace_webhooks
WHERE workspace_id = $1 AND id = $2
`

type DeleteWorkspaceWebhookParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteWorkspaceWebhook(ctx context.Context, arg DeleteWorkspaceWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceWebhook, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelWorkspaceID = `-- name: GetChannelWorkspaceID :one
SELECT workspace_id FROM channels WHERE id = $1
`

func (q *Queries) GetChannelWorkspaceID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChannelWorkspaceID, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listWorkspaceWebhooks = `-- name: ListWorkspaceWebhooks :many
SELECT id, workspace_id, url, secret, created_at, updated_at FROM workspace_webhooks
WHERE workspace_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListWorkspaceWebhooks(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceWebhook, error) {
	rows, err := q.db.Query(ctx, listWorkspaceWebhooks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceWebhook
	for rows.Next() {
		var i WorkspaceWebhook
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceWebhook = `-- name: UpdateWorkspaceWebhook :one
UPDATE workspace_webhooks
SET url = $3, secret = $4, updated_at = now()
WHERE workspace_id = $1 AND id = $2
RETURNING id, workspace_id, url, secret, created_at, updated_at
`

type UpdateWorkspaceWebhookParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
	Url         string    `json:"url"`
	Secret      string    `json:"secret"`
}

func (q *Queries) UpdateWorkspaceWebhook(ctx context.Context, arg UpdateWorkspaceWebhookParams) (WorkspaceWebhook, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceWebhook,
		arg.WorkspaceID,
		arg.ID,
		arg.Url,
		arg.Secret,
	)
	var i WorkspaceWebhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
